const LAST_UPDATED = "May 20, 2026 at 10:30 AM MDT";

const OPPORTUNITIES = [
  {
    "noticeId": "ffc2232f16f64e829ad6177e32a96acb",
    "title": "Surveillance Camera Trailer",
    "solicitationNumber": "36C26226Q0837",
    "agency": "VETERANS AFFAIRS, DEPARTMENT OF",
    "office": "262-NETWORK CONTRACT OFFICE 22 (36C262)",
    "postedDate": "2026-05-20",
    "responseDeadline": "2026-06-02T07:00:00-07:00",
    "type": "Solicitation",
    "naicsCode": "333924",
    "setAside": "Total Small Business Set-Aside (FAR 19.5)",
    "active": "Yes",
    "contacts": [{"name": "Anthony Dela Cruz", "email": "anthony.delacruz@va.gov", "phone": "562-766-2284"}],
    "uiLink": "https://sam.gov/workspace/contract/opp/ffc2232f16f64e829ad6177e32a96acb/view",
    "placeOfPerformance": {"city": {"name": "Los Angeles"}, "state": {"name": "CA"}}
  },
  {
    "noticeId": "a1b2c3d4e5f6",
    "title": "Ground Maintenance Services",
    "solicitationNumber": "W912EF26Q0045",
    "agency": "DEPT OF DEFENSE",
    "office": "US ARMY CORPS OF ENGINEERS",
    "postedDate": "2026-05-19",
    "responseDeadline": "2026-06-05T17:00:00-05:00",
    "type": "Solicitation",
    "naicsCode": "561730",
    "setAside": "",
    "active": "Yes",
    "contacts": [{"name": "Sarah Mitchell", "email": "sarah.mitchell@usace.army.mil", "phone": "503-555-0142"}],
    "uiLink": "https://sam.gov/workspace/contract/opp/a1b2c3d4e5f6/view",
    "placeOfPerformance": {"city": {"name": "Portland"}, "state": {"name": "OR"}}
  },
  {
    "noticeId": "b2c3d4e5f6a7",
    "title": "IT Support Services for Regional Office",
    "solicitationNumber": "GS35F26QA001",
    "agency": "GENERAL SERVICES ADMINISTRATION",
    "office": "GSA REGION 10",
    "postedDate": "2026-05-19",
    "responseDeadline": "2026-06-10T15:00:00-06:00",
    "type": "Combined Synopsis/Solicitation",
    "naicsCode": "541512",
    "setAside": "Total Small Business Set-Aside (FAR 19.5)",
    "active": "Yes",
    "contacts": [{"name": "James Park", "email": "james.park@gsa.gov", "phone": "206-555-0198"}],
    "uiLink": "https://sam.gov/workspace/contract/opp/b2c3d4e5f6a7/view",
    "placeOfPerformance": {"city": {"name": "Seattle"}, "state": {"name": "WA"}}
  },
  {
    "noticeId": "c3d4e5f6a7b8",
    "title": "HVAC System Replacement - Building 14",
    "solicitationNumber": "FDA26Q00234",
    "agency": "DEPARTMENT OF HEALTH AND HUMAN SERVICES",
    "office": "FDA OFFICE OF ACQUISITIONS",
    "postedDate": "2026-05-18",
    "responseDeadline": "2026-06-01T14:00:00-04:00",
    "type": "Solicitation",
    "naicsCode": "238220",
    "setAside": "8(a) Set-Aside (FAR 19.8)",
    "active": "Yes",
    "contacts": [{"name": "Linda Torres", "email": "linda.torres@fda.hhs.gov", "phone": "301-555-0167"}],
    "uiLink": "https://sam.gov/workspace/contract/opp/c3d4e5f6a7b8/view",
    "placeOfPerformance": {"city": {"name": "Silver Spring"}, "state": {"name": "MD"}}
  },
  {
    "noticeId": "d4e5f6a7b8c9",
    "title": "Janitorial Services - Federal Courthouse",
    "solicitationNumber": "TJS26Q00089",
    "agency": "DEPARTMENT OF JUSTICE",
    "office": "US MARSHALS SERVICE",
    "postedDate": "2026-05-18",
    "responseDeadline": "2026-06-08T16:00:00-05:00",
    "type": "Solicitation",
    "naicsCode": "561720",
    "setAside": "",
    "active": "Yes",
    "contacts": [{"name": "Robert Chen", "email": "robert.chen@usdoj.gov", "phone": "202-555-0134"}],
    "uiLink": "https://sam.gov/workspace/contract/opp/d4e5f6a7b8c9/view",
    "placeOfPerformance": {"city": {"name": "Chicago"}, "state": {"name": "IL"}}
  },
  {
    "noticeId": "e5f6a7b8c9d0",
    "title": "Office Furniture Procurement",
    "solicitationNumber": "GS28F26QD012",
    "agency": "GENERAL SERVICES ADMINISTRATION",
    "office": "GSA FAS NATIONAL OFFICE",
    "postedDate": "2026-05-17",
    "responseDeadline": "2026-06-02T11:00:00-05:00",
    "type": "Solicitation",
    "naicsCode": "337121",
    "setAside": "Total Small Business Set-Aside (FAR 19.5)",
    "active": "Yes",
    "contacts": [{"name": "Karen White", "email": "karen.white@gsa.gov", "phone": "817-555-0156"}],
    "uiLink": "https://sam.gov/workspace/contract/opp/e5f6a7b8c9d0/view",
    "placeOfPerformance": {"city": {"name": "Fort Worth"}, "state": {"name": "TX"}}
  },
  {
    "noticeId": "f6a7b8c9d0e1",
    "title": "Cybersecurity Assessment Services",
    "solicitationNumber": "DHS26Q00567",
    "agency": "DEPARTMENT OF HOMELAND SECURITY",
    "office": "CISA ACQUISITIONS",
    "postedDate": "2026-05-17",
    "responseDeadline": "2026-06-15T12:00:00-04:00",
    "type": "Combined Synopsis/Solicitation",
    "naicsCode": "541512",
    "setAside": "",
    "active": "Yes",
    "contacts": [{"name": "Michael Davis", "email": "michael.davis@ DHS.gov", "phone": "703-555-0189"}],
    "uiLink": "https://sam.gov/workspace/contract/opp/f6a7b8c9d0e1/view",
    "placeOfPerformance": {"city": {"name": "Arlington"}, "state": {"name": "VA"}}
  },
  {
    "noticeId": "a7b8c9d0e1f2",
    "title": "Vehicle Fleet Maintenance",
    "solicitationNumber": "DOI26Q00321",
    "agency": "DEPARTMENT OF THE INTERIOR",
    "office": "NPS REGIONAL OFFICE",
    "postedDate": "2026-05-16",
    "responseDeadline": "2026-06-06T15:00:00-06:00",
    "type": "Solicitation",
    "naicsCode": "811198",
    "setAside": "8(a) Set-Aside (FAR 19.8)",
    "active": "Yes",
    "contacts": [{"name": "Thomas Redbird", "email": "thomas.redbird@nps.gov", "phone": "505-555-0123"}],
    "uiLink": "https://sam.gov/workspace/contract/opp/a7b8c9d0e1f2/view",
    "placeOfPerformance": {"city": {"name": "Santa Fe"}, "state": {"name": "NM"}}
  },
  {
    "noticeId": "b8c9d0e1f2a3",
    "title": "Printing and Reproduction Services",
    "solicitationNumber": "ED26Q00210",
    "agency": "DEPARTMENT OF EDUCATION",
    "office": "ED OFFICE OF PROCUREMENT",
    "postedDate": "2026-05-16",
    "responseDeadline": "2026-06-03T10:00:00-04:00",
    "type": "Solicitation",
    "naicsCode": "323111",
    "setAside": "Total Small Business Set-Aside (FAR 19.5)",
    "active": "Yes",
    "contacts": [{"name": "Amanda Lee", "email": "amanda.lee@ed.gov", "phone": "202-555-0178"}],
    "uiLink": "https://sam.gov/workspace/contract/opp/b8c9d0e1f2a3/view",
    "placeOfPerformance": {"city": {"name": "Washington"}, "state": {"name": "DC"}}
  },
  {
    "noticeId": "c9d0e1f2a3b4",
    "title": "Landscaping Services - VA Medical Center",
    "solicitationNumber": "VA26Q00456",
    "agency": "VETERANS AFFAIRS, DEPARTMENT OF",
    "office": "VA NATIONWIDE ACQUISITIONS",
    "postedDate": "2026-05-15",
    "responseDeadline": "2026-06-12T13:00:00-05:00",
    "type": "Solicitation",
    "naicsCode": "561730",
    "setAside": "",
    "active": "Yes",
    "contacts": [{"name": "David Brown", "email": "david.brown@va.gov", "phone": "312-555-0145"}],
    "uiLink": "https://sam.gov/workspace/contract/opp/c9d0e1f2a3b4/view",
    "placeOfPerformance": {"city": {"name": "Hines"}, "state": {"name": "IL"}}
  }
];

const DIGEST = OPPORTUNITIES.slice(0, 5);
